In [4]:
import pandas as pd
import numpy as np
# import statsmodels.api as sm
# import statsmodels.formula.api as smf

# ---- 1. Define column names (same order as SAS input) ----
cols = [
    "id","nearc2","nearc4","nearc4a","nearc4b","ed76","ed66","age76",
    "daded","nodaded","momed","nomomed","weight","momdad14","sinmom14",
    "step14","reg661","reg662","reg663","reg664","reg665","reg666",
    "reg667","reg668","reg669","south66","work76","work78","lwage76",
    "lwage78","famed","black","smsa76r","smsa78r","reg76r","reg78r",
    "reg80r","smsa66r","wage76","wage78","wage80","noint78","noint80",
    "enroll76","enroll78","enroll80","kww","iq","marsta76","marsta78",
    "marsta80","libcrd14"
]

# ---- 2. Read flat file ----
# Adjust path and delimiter as needed (whitespace assumed)

df = pd.read_csv(
    "Data/nls.dat",
    sep=r"\s+",          # split on any whitespace
    names=cols,
    na_values=".",       # treat '.' as missing
    engine="python"
)
df.head()

,id,nearc2,nearc4,nearc4a,nearc4b,ed76,ed66,age76,daded,nodaded,...,noint80,enroll76,enroll78,enroll80,kww,iq,marsta76,marsta78,marsta80,libcrd14
0,2,0,0,0,0,7,5,29,9.94,1,...,0,0,0.0,0.0,15.0,NaN,1.0,1.0,1.0,0.0
1,3,0,0,0,0,12,11,27,8.00,0,...,0,0,0.0,0.0,35.0,93.0,1.0,4.0,4.0,1.0
2,4,0,0,0,0,12,12,34,14.00,0,...,1,0,NaN,NaN,42.0,103.0,1.0,NaN,NaN,1.0
3,5,1,1,1,0,11,11,27,11.00,0,...,0,0,NaN,0.0,25.0,88.0,1.0,NaN,5.0,1.0
4,6,1,1,1,0,12,12,34,8.00,0,...,1,0,0.0,NaN,34.0,108.0,1.0,1.0,NaN,0.0

In [5]:
df.describe()

,id,nearc2,nearc4,nearc4a,nearc4b,ed76,ed66,age76,daded,nodaded,...,noint80,enroll76,enroll78,enroll80,kww,iq,marsta76,marsta78,marsta80,libcrd14
count,3613.000000,3613.000000,3613.000000,3613.000000,3613.000000,3613.000000,3613.000000,3613.000000,3613.000000,3613.000000,...,3613.000000,3613.000000,3317.000000,3220.000000,3543.000000,2470.000000,3604.000000,3319.000000,3227.000000,3598.000000
mean,2609.781622,0.431774,0.678107,0.492112,0.185995,13.225298,10.742873,28.175201,10.002878,0.224190,...,0.106836,0.094658,0.065421,0.058385,33.489134,102.587854,2.357103,2.213619,2.104121,0.671762
std,1498.513199,0.495392,0.467267,0.500007,0.389157,2.749741,2.459085,3.171810,3.296021,0.417106,...,0.308948,0.292783,0.247304,0.234507,8.691808,15.445070,2.109638,2.005834,1.908883,0.469637
min,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,24.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,50.000000,1.000000,1.000000,1.000000,0.000000
25%,1330.000000,0.000000,0.000000,0.000000,0.000000,12.000000,9.000000,25.000000,8.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,28.000000,93.000000,1.000000,1.000000,1.000000,0.000000
50%,2574.000000,0.000000,1.000000,0.000000,0.000000,13.000000,11.000000,28.000000,9.940000,0.000000,...,0.000000,0.000000,0.000000,0.000000,34.000000,104.000000,1.000000,1.000000,1.000000,1.000000
75%,3908.000000,1.000000,1.000000,1.000000,0.000000,16.000000,12.000000,31.000000,12.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,40.000000,113.000000,4.000000,4.000000,4.000000,1.000000
max,5225.000000,1.000000,1.000000,1.000000,1.000000,18.000000,18.000000,34.000000,18.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,56.000000,156.000000,6.000000,6.000000,6.000000,1.000000

If we compare our dataset with the info provided in the dataset card, we can see that we read correclty the data, as we have the same values for statistics.